export const donatePage = {
  title: "Donate & Support EMA Fight Back",
  tagline: "Help Us Empower Children, Families & Communities With Lifesaving Safety Skills",
  overview: [
    "Your support helps EMA Fight Back continue its mission to teach People Safety, Bullying Prevention, Emotional Safety, and Self-Defense to children, teens, women, seniors, special needs students, schools, and communities across India.",
    "With your donation, we can reach those who need us most — especially underprivileged schools, rural areas, women’s groups, and vulnerable populations.",
    "Together, we can create a safer, stronger, more confident society.",
  ],
  whyTitle: "Why Your Support Matters",
  whyIntro: "Many people across India still do not have access to:",
  why: [
    "Bullying prevention training",
    "Personal safety education",
    "Women’s self-defense",
    "Emotional safety tools",
    "Senior citizen safety training",
    "Special needs safety programs",
    "School staff safety development",
  ],
  whyClose: [
    "Your contribution helps us provide free or subsidized training to those who cannot afford it.",
    "Every donation directly supports life-saving education.",
  ],
  impactTitle: "How Your Donation Makes an Impact",
  impact: [
    { amount: "₹500", body: "Covers safety training material for one child." },
    { amount: "₹1,000", body: "Supports a child from a low-income family to attend a workshop." },
    { amount: "₹5,000", body: "Funds a safety session for a small group of special needs students." },
    { amount: "₹10,000", body: "Funds a women’s safety workshop for a community or society." },
    { amount: "₹25,000", body: "Sponsors a complete safety program for an underprivileged school." },
    { amount: "₹50,000+", body: "Become a Major Supporter and help bring long-term safety programs to multiple communities." },
  ],
  impactClose: "No contribution is too small — every bit counts.",
  waysTitle: "Ways You Can Support Us",
  ways: [
    {
      title: "1. Donate Online",
      body: "Make a one-time or monthly contribution to support our ongoing programs.",
      cta: "Donate Now – Secure Payment",
      href: "/contact",
    },
    {
      title: "2. Sponsor a Program",
      body: "Choose a program to sponsor: child safety workshops, school safety series, women’s self-defense, senior citizen programs, or special needs training.",
      cta: "Sponsor a Program",
      href: "/contact",
    },
    {
      title: "3. CSR Partnerships (Corporate Social Responsibility)",
      body: "We partner with corporates to deliver school safety programs, women’s safety workshops, community outreach projects, and large-scale training missions. This is ideal for companies looking to create social impact and community upliftment.",
      cta: "CSR Partnership Inquiry",
      href: "/book#organization",
    },
    {
      title: "4. Volunteer With Us",
      body: "Help us with workshop support, social media, event management, outreach and awareness, documentation & content.",
      cta: "Become a Volunteer",
      href: "/contact",
    },
    {
      title: "5. Fundraise for a Cause",
      body: "Organize a fundraiser with your school, college, corporate team, society, friend group, club or community. We provide all required materials and support.",
      cta: "Contact Us",
      href: "/contact",
    },
  ],
  changeTitle: "Your Contribution Creates Real Change",
  changeIntro: "Your support allows us to:",
  change: [
    "Teach more children how to stay safe",
    "Train parents to protect their families",
    "Empower women with self-defense",
    "Support senior citizens",
    "Provide inclusive training for special needs groups",
    "Build safer schools and communities",
    "Train instructors to expand our mission",
  ],
  changeClose: "Every life touched is protected… because of you.",
  transparencyTitle: "Transparency & Accountability",
  transparencyIntro: "We ensure:",
  transparency: [
    "100% transparency in how funds are used",
    "Regular impact reports for sponsors",
    "Photos & updates from supported programs",
    "Clear documentation for CSR partners",
  ],
  transparencyClose: "Your trust is our responsibility.",
  close: "Support the Mission. Save Lives. Make India Safer.",
};
